version: '3.8'

services:
  zerto-exporter:
    image: zerto-exporter
    container_name: zerto-exporter
    ports:
      - 8080:8080

  zerto-prometheus:
    image: prom/prometheus:latest
    container_name: zerto-prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  zerto-grafana:
    image: grafana/grafana-oss:latest
    container_name: zerto-grafana
    ports:
      - 3000:3000
