global:
  scrape_interval: 15s

scrape_configs:
  - job_name: zerto-exporter
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 5s
    static_configs:
      - targets: ["zerto-exporter:8080"]
